version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    # volumes:
        # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        # - ./db:/docker-entrypoint-initdb.d